### PR TITLE
View type composition

### PR DESCRIPTION
**Pull request by tower120**
This PR implements this https://github.com/ericniebler/range-v3/issues/932#issuecomment-483304960

Interface is following:
```cpp
using List = std::vector<std::unique_ptr<int>>;
List list;

// all views in chain unary constructible
using Get = compose_view<List, indirect_view, const_view >;
Get get(){
    return list | view::indirect | view::const_;
}
Get get2(){
    return Get{list};
}
```
non-unary constructible:
```cpp
struct Fn{
    const int& operator()(const int& i) const { return i; }
};
using Get = compose_view<List, compose_bind<transform_view, Fn>::type >;
Get get(){
    return list | view::transform(Fn{});
}
/*Get get2(){
    return Get{list};  // impossible, for now
}*/
```

### CODE REVIEW

**Comment by tower120** [comment]
View composition without data source attached (aka `view::indirect | view::tail`) possible with this https://github.com/ericniebler/range-v3/issues/1158 implemented :

```cpp
template<class Rng>
struct filter_view : compose_view<Rng, drop_view, const_view>{
    filter_view() = default;
    explicit filter_view(Rng&& rng, int n)
        : filter_view::compose_view(std::move(rng) | view::drop(n) | view::const_) {}
};

using Get = compose_view<List, filter_view>;
Get get(){
    return list | pipe<filter_view>(1);
}
```

**Comment by johelegp** [comment]
What problems do you perceive with regards to the types of `view::X` differing from `X_view`? I also find it unfortunate that `range_fwd.hpp` does not have declarations of all views, which would see increased use with this feature.

**Comment by tower120** [comment]
> What problems do you perceive with regards to the types of view::X differing from X_view? 

I'm not sure I understand you. `view::X` is not a type.

>  I also find it unfortunate that range_fwd.hpp does not have declarations of all views

Don't understand, either...

----

Motivation example for `compose_view` is following:
```cpp
// .hpp
class Widget;   // forward declare only

using List = std::vector<std::unique_ptr<Widget>>;
List list;

using Get = compose_view<List, indirect_view, const_view >;
Get get();  // it is impossible to have auto return type function with implementation in .cpp !!

// --------------------------------------------------

// .cpp
#include "Widget.h"   // now include concrete class

Get get(){
   return Get{};
}
```

- breaking cyclic "include" dependency.
- moving implementation to .cpp . Have sense with parametric (non-unary) views drop / drop_last / etc..

**Comment by johelegp** [comment]
Yeah. I understand the benefits and would like to have such functionality available.

> > What problems do you perceive with regards to the types of view::X differing from X_view?
> 
> I'm not sure I understand you. `view::X` is not a type.

I mean, the composition should use `view::X_fn` rather than `X_view` so that even when the return type of `view::X` isn't a specialization of `X_view`, things work as expected.

> > I also find it unfortunate that range_fwd.hpp does not have declarations of all views
> 
> Don't understand, either...

Just some wrong thought. Since a benefit of this feature is improved compile times for users, I thought about using it with forward declarations of the views for further improvement. But then the header wouldn't be self-contained. Please, dismiss this.

**Comment by tower120** [comment]
> I mean, the composition should use view::X_fn rather than X_view so that even when the return type of view::X isn't a specialization of X_view, things work as expected.

So... you ask how it works (`drop_view` in type, while `drop` in construction)?

**Comment by johelegp** [comment]
No. Consider your example [above](https://github.com/ericniebler/range-v3/pull/1155#issuecomment-487009531).

> ```c++
> template<class Rng>
> struct filter_view : compose_view<Rng, drop_view, const_view>{
>     filter_view() = default;
>     filter_view(Rng&& rng, int n)
>       : filter_view::compose_view(std::forward<Rng>(rng) | view::drop(n) | view::const_) {}
> };
> 
> using Get = compose_view<List, filter_view>;
> Get get(){
>     return list | pipe<filter_view>(1);
> }
> ```

If `Rng` is `std::string_view`, `view::drop(n)` returns `subrange<iterator_t<std::string_view>, sentinel_t<std::string_view>>` and not `drop_view<all_t<std::string_view>>`. That would result in a compile-time error.

**Comment by tower120** [comment]
@johelegp Now looking at `view/drop.hpp ` I see what you mean. There is special case - and that special case handled not by view, but by "adaptor closure object" (drop_fn). I have feeling that is wrong... Adaptor closure object must be view "wrapper"  - and nothing more... All that logic for special cases must be handled by view itself... It's counter-intuitive after all! How it come that `drop_view(my_string_view, 2)` and `my_string_view | drop(2)` is a different things?

_But in case - if that is not view implementation mistake - compose_view can work with X_fn instead of X_view..._

**Comment by johelegp** [comment]
> _But in case - if that is not view implementation mistake - compose_view can work with X_fn instead of X_view..._

Yes, that's allowed. So that change would be for the best. Look at the description of the various `std::ranges::view`s to see why it can be useful for the types to differ.

**Comment by tower120** [comment]
@johelegp at a first glance - looks like a pure madness to me! I don't see why http://www.eelis.net/c++draft/range.adaptors#range.all can't have `all_view` which would do all that dispatching. why `/*undefined type*/` range adaptor object do all that, instead?

I need to reconsider `compose_view` design...

That's not that pretty now:
```cpp
using Get = compose_view<List, decltype(view::indirect), decltype(view::const_) >;
```

**Comment by tower120** [comment]
There is probably more "sane", standard compatible (I hope!) way of doing this.

```cpp
using Get = compose_view<List, view::indirect, view::const_ >;
```

By working with `template<auto&...>` http://coliru.stacked-crooked.com/a/d07c1f442bb1b90f

**Comment by johelegp** [comment]
That's great! But it doesn't work on C++14. If you're going to require `decltype`, might as well do it on the outside so that it's only needed once.
```C++
using Get = compose_view<List, decltype(view::indirect), decltype(view::const_) >;
using Get = decltype(compose_view<List>(view::indirect, view::const_));
```

**Comment by tower120** [comment]
@johelegp Mmmm... Can't it be C++17 only?

**Comment by johelegp** [comment]
You'd have to ask @ericniebler.

**Comment by tower120** [comment]
Сontinued here https://github.com/ericniebler/range-v3/pull/1172

**Pull request closed without merging**
