### PR TITLE
Conan recipe

### PR DESCRIPTION
**Pull request by lasote**
Hi @ericniebler

I've created a conan package recipe for you. You can test it by:

- Install conan (https://conan.io/downloads)
- Execute ``conan test_package``. It will build the package and run an example I copied from your docs linking with the conan package.

If you want to upload to conan.io:

- Register in conan.io with the **ericniebler** username
- `conan export ericniebler/stable` It register the recipe in the client cache.
- `conan upload range-v3/latest@ericniebler/stable -r conan.io` 

Finally I used "latest" as the package version, because you mention that you are not versioning the releases. Feel free to change username, channel etc.

The files contained in the PR are:

- `conanfile.py`:  Main recipe for you range-v3 library. Just takes the headers and pack them, very easy.
- `test_package` folder: An example using range-v3, it helps to test that the package is built correctly, the package name could be different, you could invoke `conan test_package -f FOLDER` in another folder not named test_package. 

Currently is saving in the recipe all your headers, so in every master push, if you would want to update the package you would need to `conan export` and `conan upload` again. But there is another possibility, we can keep the recipe without the sources (removing the export in the conanfile.py) and use a `source` method that will pull the source code in every install. So every time a user installs range-v3 package it will download the latest source code. Tell me if you want this approach or any other change.

Finally you can go to your package homepage in conan.io and copy the badge code to your readme if you want. People will know that they can use your library with conan.io.

Thanks
Luis

### CODE REVIEW

**Comment by lasote** [comment]
Execute  `conan --version`

**Comment by ericniebler** [comment]
```
$conan --version
Conan version 0.8.6
```

**Comment by lasote** [comment]
Install a newer version. 0.8.6 is obsolete. Latest is 0.14.1.

**Comment by ericniebler** [comment]
I did `brew install conan` on MacOS and that's what I got. It's what your download page recommends.

**Comment by lasote** [comment]
Did you a brew update first?

**Comment by ericniebler** [comment]
Ah. Thanks for that. It works now.

**Comment by ericniebler** [comment]
Could you please add license and copyright information to the files you're adding?

**Comment by lasote** [comment]
Sure, I can do it but please tell me what you prefer. I don't have any interest about owning the copyright or any special license. What you want. I could sign a CLA and give you all the rights.

**Comment by ericniebler** [comment]
Open any file in the repo and copy/paste the text of the Boost Software License and the copyright notice. Change the copyright to have your name, since you wrote the code.

**Comment by lasote** [comment]
I added the text but kept your name in the example.cpp, because it's a copy paste from your docs.

**Comment by ericniebler** [comment]
Awesome, thanks!

**Comment by ericniebler** [comment]
@lasote, I just followed the steps to upload `range-v3/latest@ericniebler/stable` to conan.io, but when I search for the package on conan.io, I don't find it. Does it take a while for packages to show up in the search results?

**Comment by lasote** [comment]
yep. It takes some minutes to index the entry.

**Comment by lasote** [comment]
Did you a brew update first?

**Pull request merged**
