### PR TITLE
make box trivially_default_constructible

### PR DESCRIPTION
**Pull request by tower120**
This PR makes box trivially_default_constructible if possible.
Fix https://github.com/ericniebler/range-v3/issues/1093

### CODE REVIEW

**Comment by tower120** [comment]
Argh. It's just too much code for such a simple thing.

Probably it would be more reasonable just to remove `std::is_trivial<T>` from `box_compress::coalesce` requirements.

**Comment by ericniebler** [comment]
IIRC @CaseyCarter is the one that added the `coalesce` strategy to `box`. Maybe he could cast an eye over this.

**Comment by CaseyCarter** [comment]
Ack, I $&#@$@-ed up the branch with a bunch of commits from `master` trying to add bda19f7. Sorry about that.

In any case: I've removed all of the `box_ebo_` complexity: trivial default construction isn't a design goal for `box`, since it must value-initialize its `Element`. The only change that's needed for #1093 is the defaulted default constructor for the `coalesce` specialization of `box` (I have no idea why I didn't default it in the first place).

**Comment by tower120** [comment]
@CaseyCarter Can trivial-constructivity requirement for `coalesce` be lifted too?

```cpp
    struct Op {
        Op() noexcept(some_condition) {};   // !!! this will prevent coalesce strategy now.
    };
    struct Op2 {};

    struct payload { void* v; };
    struct base_adaptor {};

    struct RANGES_EMPTY_BASES A : base_adaptor, private box<Op, A> {};
    struct RANGES_EMPTY_BASES B : base_adaptor, private box<Op2, B> {};

    using P  = compressed_pair<A, payload>;
    using P2 = compressed_pair<B, P>;

    // checks will fail
    CHECK(sizeof(P) == sizeof(payload));
    CHECK(sizeof(P2) == sizeof(P));
```

**Comment by CaseyCarter** [comment]
> @CaseyCarter Can trivial-constructivity requirement for `coalesce` be lifted too?

That would be problematic for a couple of reasons: 
1. An empty type with non-trivial initialization is likely engaging in some kind of funny business that would break if we coalesce multiple instances into a single instance.
2. We *really* don't want to invisibly introduce the Static Initialization Order fiasco into a program by defining a static storage duration variable with dynamic initialization. I won't assert that there's no way to determine that a type has `constexpr` default-initialization, but I can't think of one of the top of my head.

**Pull request merged**
