### PR TITLE
Add clang 3.8 to the test matrix.

### PR DESCRIPTION
**Pull request by CaseyCarter**
...with working sanitizers!

Specifically: adds clang 3.8 configs with C++11/14, Debug/Release, ASAN=On only.

### CODE REVIEW

**Comment by ericniebler** [comment]
Looks like clang 3.8 release build are failing.

**Comment by CaseyCarter** [comment]
Yes. I'm trying to replicate the Travis setup to reproduce.

**Comment by CaseyCarter** [comment]
The errors appear to be an interaction between ASAN and valgrind. The ASAN setup code blows up and complains that something has been already been mapped - i conjecture by valgrind - into address space that it wants.

I managed to reproduce it, but an hour or so of investigation turned up no simple solution. I'm not motivated to invest more time, so for now I disabled the valgrind tests for ASAN compiles.

**Comment by ericniebler** [comment]
Sounds reasonable. Thanks.

**Pull request merged**
