### PR TITLE
fix missing includes forever

### LINKED ISSUE #182: Consider testing includes
Boost.Hana's CMake automatically tests that each header file is able to include itself by creating a test for each header file that just:

```c++
#include <header_file>
int main() { return 0; }
```

Is there interest in adding something like this to range-v3?

### PR DESCRIPTION
**Pull request by gnzlbg**
All kudos go to Louis Dione for writing the CMake scripts of Boost.Hana. 

This just adapts his scripts for range-v3; all mistakes introduced are only mine.

- fix missing includes caught by the tests.

- replace `# warning` with `#pragma message` because `-Werror, -Wpedantic` complains that 
  `# warning` is a language extension (this prevents some new tests from compiling).

Closes #182  .

### CODE REVIEW

**Comment by rhalbersma** [comment]
There is a CMake macro `check_include_file_cxx` that does this. Just `glob_recurse` to get all headers and feed them to this macro one by one.

**Comment by rhalbersma** [comment]
Another thing: why not write another `include<header>` to also test for header guards?

**Comment by ericniebler** [comment]
Can you please squash these two commits?

**Comment by ericniebler** [comment]
> There is a CMake macro `check_include_file_cxx` that does this. Just `glob_recurse` to get all headers and feed them to this macro one by one.

Sounds like a worthwhile simplification to me.

**Comment by gnzlbg** [comment]
> Can you please squash these two commits?

Done. 

> There is a CMake macro check_include_file_cxx that does this. Just glob_recurse to get all headers and feed them to this macro one by one.

I tried to look up what that macro does but the docs just say:

> Check if the include file exists.

Which is not the same, but the [source file](https://github.com/Kitware/CMake/blob/master/Modules/CheckIncludeFileCXX.cmake) uses `try_compile` to try and compile a file. 

It is not clear to me if it tries to compile the file by passing it `-I/path/to/include/file.hpp` or if it actually adds `#include <path/to/include/file.hpp>` to the source file.

**Comment by ilyapopov** [comment]
Actually, that variable is used, but implicitly. In [CheckIncludeFileCXX.cmake](https://github.com/Kitware/CMake/blob/master/Modules/CheckIncludeFileCXX.cmake) on line 55 there is a call to `configure_file`, which takes [this template](https://github.com/Kitware/CMake/blob/master/Modules/CheckIncludeFile.cxx.in) and substitutes the variable `CHECK_INCLUDE_FILE_VAR` from the current scope. Then the resulting source file is passed to `try_compile` for compilation. Thus this macro does exactly  what we want.

**Comment by gnzlbg** [comment]
@ilyapopov thanks for the explanation!

**Comment by ericniebler** [comment]
@gnzlbg Will you be updating the patch with the CMake built-in?

**Comment by gnzlbg** [comment]
@ericniebler Yes, don't merge this yet.

**Comment by gnzlbg** [comment]
So I've got `check_include_file_cxx` to work. 

I don't know if I like this solution better yet, but it is simpler than the previous one.

What makes me doubt is that:
- one has to re-run cmake for this to work and it only works at configure time, 
- it takes a long time to compile all the headers and AFAIK this can't be parallelized.

Louis solution can be parallelized by just doing `make test.headers -j N`, and it can be run multiple times (`make test.headers`) but the list of files is only updated at configure time (so it isn't perfect either).

Anyhow I just wanted the missing includes problem fixed forever, and this achieves it. If it turns out to be too annoying or something we could introduce a cmake variable to enable/disable this in the future.

**Comment by ericniebler** [comment]
Thanks!

**Comment by ericniebler** [comment]
I'm now getting this error when I configure:

fatal: Not a git repository (or any parent up to mount point /cygdrive/c)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
-- Looking for C++ include meta/meta.hpp
-- Looking for C++ include meta/meta.hpp - not found
CMake Error at CMakeLists.txt:102 (message):
  Compilation of header meta/meta.hpp failed


-- Configuring incomplete, errors occurred!

**Comment by ericniebler** [comment]
Reverted.

**Comment by gnzlbg** [comment]
meta.hpp not found? Is this in linux, mac or windows?

**Comment by ericniebler** [comment]
Cygwin on windows

**Comment by gnzlbg** [comment]
And I assume meta is in the include/ directory of range-v3 right?

Typically CMake writes an error file in the build_dir/CMakeFiles/CMakeTmp/
. Those files might be useful to help figure out what goes wrong.

**Comment by ericniebler** [comment]
That directory doesn't exist. Probably since I reverted the commit and reconfigured so I could work on something else.

**Comment by gnzlbg** [comment]
The work around would be to add a cmake flag for it, and check the headers only if it's set. 

The cmake file uses the "portable" `check_include_file_cxx` way, maybe the original solution didn't have that problem. 

From that error message the only thing I get is that cmake was not able to either find meta.hpp or compile it. 

One could set up appveyor for range-v3, it's like travis, but with windows, and has mingw.

**Comment by tamaskenez** [comment]
There's a surplus slash after the `-I` switch in the `check_include_file_cxx` command:

    check_include_file_cxx("${_relative}" ${_relative}_FOUND "-I/${CMAKE_SOURCE_DIR}/include")

If I remove it, it works again.
Another, maybe more elegant way to write it would be:

    set(CMAKE_REQUIRED_INCLUDES ${CMAKE_SOURCE_DIR}/include)
    ....
    check_include_file_cxx("${_relative}" ${_relative}_FOUND)

Let me know if I should send a PR with the fix.

**Comment by gnzlbg** [comment]
Thanks @tamaskenez , 

I am giving this a try here: https://travis-ci.org/gnzlbg/range-v3/builds/7070363 . 

Can anybody check if that branch works on windows under Cygwin as is?

**Comment by tamaskenez** [comment]
[a3c9527e](https://github.com/gnzlbg/range-v3/commit/a3c9527e83e505c1863d24ac952095fee494b042) works under Cygwin, cmake 3.1.2, gcc 4.9.2, includes found, all tests pass

**Comment by gnzlbg** [comment]
Superseeded by #192 .

**Pull request merged**
