### PR TITLE
New concepts syntax

### PR DESCRIPTION
**Pull request by CaseyCarter**
Porting changes from master.

### CODE REVIEW

**Comment by ericniebler** [comment]
Looks like this broke Appveyor. 😑

**Comment by CaseyCarter** [comment]
I know why it's broken: name resolution for `get(x)` fails when `x` is `tagged<std::tuple<Ts...>, /*...*/>` because the conversion to `std::tuple<Us...>` necessary for template argument deduction against `std::get(std::tuple<Us...>)` to succeed is ambiguous. What I don't know is why it didn't show up before.

**Comment by CaseyCarter** [comment]
Unrelated: What's with the `constexpr /*c++14*/`s? Doesn't this branch require C++14?

**Comment by CaseyCarter** [comment]
> the conversion to `std::tuple<Us...>` necessary for template argument deduction against `std::get(std::tuple<Us...>)` to succeed is ambiguous. What I don't know is why it didn't show up before.

Very much related: I despise MSVC's `tuple`.

**Comment by ericniebler** [comment]
> Doesn't this branch require C++14?

Yes.

**Pull request merged**
