### PR TITLE
constexpr friendly view::view

### PR DESCRIPTION
**Pull request by tower120**
This PR partially fix/implement this https://github.com/ericniebler/range-v3/issues/1169.
`view::view` are now constexpr-friendly.

---

Now what we lack is constexpr "bind". Our options are:
  * use lambdas instead of `std::bind`. Lambdas are constexpr in C++17.
  * use third-party constexp bind. Like https://github.com/bolero-MURAKAMI/Sprout/blob/master/sprout/functional/bind/bind.hpp from https://github.com/bolero-MURAKAMI/Sprout/ . What about copyright clashes?
  * write our own constexpr friendly bind. (I don't think I can/want do this)

### CODE REVIEW

**Comment by ericniebler** [comment]
> Now what we lack is constexpr "bind".

We don't. There is nothing `bind` does that can't be done better with hand-rolled callables. Better compile times too, I'll wager.

This PR needs a rebase on master and a `clang-format`.

**Comment by tower120** [comment]
> There is nothing bind does that can't be done better with hand-rolled callables.

What is "hand-rolled callables"?

**Comment by ericniebler** [comment]
> What is "hand-rolled callables"?

A struct with a function call operator. That's what `std::bind` returns, after all. We don't need `std::bind` to do that.

**Comment by tower120** [comment]
> A struct with a function call operator. 

So you want a Functor. That will work of course, don't know how large that will be though... Will see.

> This PR needs a rebase on master and a clang-format

Does CI test for compliance with clang-format? (I don't see nothing special in travis.yml) 
How should I know that whole project formatted right?

**Comment by ericniebler** [comment]
> So you want a Functor.

I know what you meant, and yes, but "Functor" means something very specific in math and functional programming (https://en.m.wikipedia.org/wiki/Functor), so I do my part to about (ab)using that term in C++ to say "function object".

**Comment by tower120** [comment]
I can't comply with your `.clang-format`. At first `BraceWrapping.AfterCaseLabel` property is too new and not supported even by `clang-format-5.0`. At second (after commenting that option) - formatting gives absolutely insane results like:
```
int 
main()
{
```

**Comment by ericniebler** [comment]
> formatting gives absolutely insane results like:
> 
> ```
> int 
> main()
> {
> ```

I agree that's insane and surprising. It appears to be a clang-format bug, where an explicitly specified option (in this case, `AlwaysBreakAfterReturnType`) is not overriding the `BasedOnStyle`. I'll see if I can work around it.

I have filed the bug here: https://bugs.llvm.org/show_bug.cgi?id=42077

**Comment by ericniebler** [comment]
I have fixed the .clang-format file. Please rebase on master and try again. You'll still need to delete the `BraceWrapping.AfterCaseLabel` line if you're not using building clang-format from trunk.

**Comment by tower120** [comment]
Emmm.... How to make this clang-format friendly?

```cpp
        CPP_template(typename Pipe0, typename Pipe1)
            (requires is_pipeable_v<Pipe0> && is_pipeable_v<Pipe1>)
        constexpr friend auto operator|(Pipe0 pipe0, Pipe1 pipe1)
        {
            return make_pipeable(detail::composed_pipe<Pipe0, Pipe1>{pipe0, pipe1});
        }
```

It becomes:

```cpp
        CPP_template(typename Pipe0, typename Pipe1)(
            requires is_pipeable_v<Pipe0> && is_pipeable_v<Pipe1>) constexpr friend auto
        operator|(Pipe0 pipe0, Pipe1 pipe1)
        {
            return make_pipeable(detail::composed_pipe<Pipe0, Pipe1>{pipe0, pipe1});
        }
```

I tried to put ` //` at the end of each line, but that didn't help.

**Comment by ericniebler** [comment]
It ain't a thing of beauty, but it works:

```c++
CPP_template(typename Pipe0, typename Pipe1)(
    requires is_pipeable_v<Pipe0> && is_pipeable_v<Pipe1>) // clang-format off
constexpr friend auto operator|(Pipe0 pipe0, Pipe1 pipe1) // clang-format on
{
    return make_pipeable(detail::composed_pipe<Pipe0, Pipe1>{pipe0, pipe1});
}
```

**Comment by tower120** [comment]
```cpp
CPP_template(typename Pipe0, typename Pipe1)(
    requires is_pipeable_v<Pipe0> && is_pipeable_v<Pipe1>) // clang-format off
```

But It still moves bracket to the previous line. Maybe better:
```cpp
        CPP_template(typename Pipe0, typename Pipe1) // clang-format off
            (requires is_pipeable_v<Pipe0> && is_pipeable_v<Pipe1>)
        constexpr friend auto operator|(Pipe0 pipe0, Pipe1 pipe1) // clang-format on
        {
            return make_pipeable(detail::composed_pipe<Pipe0, Pipe1>{pipe0, pipe1});
        }
```
?

Or even just wrap whole function, for sake of readability:
```cpp
        // clang-format off
        CPP_template(typename Pipe0, typename Pipe1) 
            (requires is_pipeable_v<Pipe0> && is_pipeable_v<Pipe1>)
        constexpr friend auto operator|(Pipe0 pipe0, Pipe1 pipe1)
        {
            return make_pipeable(detail::composed_pipe<Pipe0, Pipe1>{pipe0, pipe1});
        }
        // clang-format on
```

**Comment by ericniebler** [comment]
> ```c++
> CPP_template(typename Pipe0, typename Pipe1)(
>     requires is_pipeable_v<Pipe0> && is_pipeable_v<Pipe1>) // clang-format off
> ```
> 
> But It still moves bracket to the previous line.

Are you upset about the open paren at the end of the first line? If you look through the rest of range-v3, you'll see it's done that way consistently. I'm not attached to it, but it has the nice property that the line with the `requires` on it reads well.

**Comment by tower120** [comment]
And now this:

```cpp
        CPP_template(typename Arg, typename Pipe)
             (requires !is_pipeable_v<Arg> && is_pipeable_v<Pipe>) // clang-format off
        constexpr friend auto operator|(Arg &&arg, Pipe pipe) // clang-format on
        {
            return pipeable_access::impl<Pipe>::pipe(static_cast<Arg &&>(arg), pipe);
        }
```
Becomes this:
```cpp
        CPP_template(typename Arg, typename Pipe)(requires !is_pipeable_v<Arg> &&
                                                  is_pipeable_v<Pipe>) // clang-format off
        constexpr friend auto operator|(Arg &&arg, Pipe pipe) // clang-format on
        {
            return pipeable_access::impl<Pipe>::pipe(static_cast<Arg &&>(arg), pipe);
        }
```

----

Three possible solutions:

1.
```cpp
        CPP_template(typename Arg, typename Pipe) // clang-format off
             (requires (!is_pipeable_v<Arg>) && is_pipeable_v<Pipe>)
        constexpr friend auto operator|(Arg &&arg, Pipe pipe) // clang-format on
        {
            return pipeable_access::impl<Pipe>::pipe(static_cast<Arg &&>(arg), pipe);
        }
```

2.
```cpp
        // clang-format off
        CPP_template(typename Arg, typename Pipe)
             (requires (!is_pipeable_v<Arg>) && is_pipeable_v<Pipe>)
        constexpr friend auto operator|(Arg &&arg, Pipe pipe)
        // clang-format on
        {
            return pipeable_access::impl<Pipe>::pipe(static_cast<Arg &&>(arg), pipe);
        }
```

3.
```cpp
        // clang-format off
        CPP_template(typename Arg, typename Pipe)
             (requires (!is_pipeable_v<Arg>) && is_pipeable_v<Pipe>)
        constexpr friend auto operator|(Arg &&arg, Pipe pipe)
        {
            return pipeable_access::impl<Pipe>::pipe(static_cast<Arg &&>(arg), pipe);
        }
        // clang-format on
```

P.S. Maybe there is some clang-format guards that can be put inside macro?... I'm sure it breaks the line because macro considered as one large string.

**Comment by ericniebler** [comment]
Please use this, which formats just fine for me:

```c++
CPP_template(typename Arg, typename Pipe)( //
    requires !is_pipeable_v<Arg> && is_pipeable_v<Pipe>) // clang-format off
constexpr friend auto operator|(Arg &&arg, Pipe pipe)       // clang-format on
{
    return pipeable_access::impl<Pipe>::pipe(static_cast<Arg &&>(arg), pipe);
}
```

**Pull request merged**
