### PR TITLE
Issue 952

### PR DESCRIPTION
**Pull request by CaseyCarter**

### CODE REVIEW

**Comment by CaseyCarter** [comment]
This fixes the symptom - the manifestation in #952, but not the root cause. Something is misconstrained in the `view_adaptor` machinery. Removing the exception specifications from `range_access::begin_cursor`, the `view_adaptor::begin_cursor` overloads, and `view_adaptor::begin_cursor_` also corrects the problem in #952.

**Comment by CaseyCarter** [comment]
> Either something is misconstrained in the `view_adaptor` machinery

There's an order-of-instantiation dependency: changing the return type of `view_adaptor::begin_cursor` from `adaptor_cursor_t<D>` to `decltype(adaptor_cursor_t<D>{})` brings the hard error back even with the exception specifications disabled. I'm tempted to simply remove the exception specifications and call it fixed.

**Comment by CaseyCarter** [comment]
I'm going to merge this, and continue investigating the `view_adaptor` weirdness as a separate issue.

**Comment by ericniebler** [comment]
Thanks for this!

**Pull request merged**
