### PR TITLE
Fix post increment of counted iterator

### PR DESCRIPTION
**Pull request by YehezkelShB**
When using conuted_iterator with an input iterator that has void-returning post increment operator, the post incrementing of counted_iterator doesn't decrement its counter.

This PR adds a test that demonstrates the issue and then adds the missing line to fix it.

### CODE REVIEW

**Comment by YehezkelShB** [comment]
Working on a wider change in counted_iterator we want to propose (see P2406 for more details), we noticed this issue.
We hope this supports the claim that no one is using counted_iterator with input iterators right now (at least with post increment operator), which makes it easier to propose other, possibly-breaking, changes we consider for P2406 :)

**Comment by YehezkelShB** [comment]
@ericniebler I'd appreciate your feedback here. This is just adding one line + a simple test to demonstrate the bug/fix

**Comment by ericniebler** [comment]
Apologies, running your tests now, but change looks good.

**Comment by ericniebler** [comment]
Why are tests still pending?

**Comment by YehezkelShB** [comment]
> Why are tests still pending?

> Can't find any online and idle self-hosted runner in the current repository, account/organization that matches the required labels: 'ubuntu-16.04'

Seems like 16.04 isn't available there anymore? Tests running on 20.04 did run

**Comment by YehezkelShB** [comment]
GitHub Actions : Ubuntu 16.04 LTS virtual environment will be removed on September 20, 2021

https://github.blog/changelog/2021-04-29-github-actions-ubuntu-16-04-lts-virtual-environment-will-be-removed-on-september-20-2021/

**Comment by YehezkelShB** [comment]
Changing it with #1671

**Comment by YehezkelShB** [comment]
@ericniebler Tests passed now. Do you want me to rebase this branch on latest master or the merge is OK?

**Pull request merged**
