### PR TITLE
Enable compile with strict clang

### PR DESCRIPTION
**Pull request by bradleygibson**
range-v3 will not compile when compiling under Clang (I am on v4.0.0, but no reason to believe the same won't happen on any version) with -Weverything -Werror*.  I ignored the warnings that the compiler reported, initially at the highest level (all.hpp), but this did not seem to be effective.  I then went one level down (same result), so I ended up disabling warnings in the offending files themselves.

If you know of a better way to do this, let me know, and I will re-submit the PR.

*The exact set of warning switches I am using for my project is `-Weverything -Werror -Wno-c++98-compat -Wno-c++98-compat-pedantic -Wno-newline-eof -Wno-exit-time-destructors -Wno-weak-vtables`.  This PR suppresses any remaining warnings in range-v3 only.

### CODE REVIEW

**Comment by pfultz2** [comment]
Whats the point of ignoring the warnings? The warnings are not enabled in the CI.

**Comment by gnzlbg** [comment]
> range-v3 will not compile when compiling under Clang with -Weverything -Werror

@bradleygibson This is deliberate. A lot of the warnings there don't make much sense. If you try to do the same with libc++ or libstdc++ you will realize that they don't compile with `-Weverything -Werror` either. The difference is that you are probably including your standard library using `-isystem` instead of just `-I`, and warnings are ignored for system libraries.

**Comment by gnzlbg** [comment]
@pfultz2 If we decide compiling `-Weverything -Werror` with clang/gcc/... is something worth pursuing, I don't really see a better way of doing it than with something "like" this PRs (but with  the logic for pop/pushing offending warnings abstracted away to some config files instead of duplicating it on every file). We then would also need to enable `-Weverything -Werror` in Travis CI, and test with _all_ compiler versions in debug and optimized builds, since the set of warnings in `-Weverything` changes form version to version, and some warnings only trigger with/without optimizations (at least in clang).

I don't really care (since I just use `-isystem` for range-v3 and am done with it), but if somebody wants to do the work I wouldn't mind as long as the result is easy to maintain and it doesn't clutter every file with lots of warning disabling/reenabling logic.

**Comment by bradleygibson** [comment]
@gnzlbg agreed.  BTW, some older versions of GCC didn't like this, so that would also need to be factored in to the refactored version.

I think your -isystem suggestion is the most pragmatic for now.

**Comment by gnzlbg** [comment]
Cross-referencing this with the respective issues for the people of the future:  #451 #195 #2

**Comment by ericniebler** [comment]
The diagnostics at these very high warning levels tend to be uninteresting. We could spend all of our time playing whack-a-mole with them for every version of every compiler. I'm seriously not interesting in doing that, and I don't much care to have the range-v3 source code littered with macro work-arounds like in this patch. I've even seen people _introduce bugs_ and make code less efficient and harder to read just to silence some misguided compiler warning. It's the tail wagging the dog.

I think compiling clean with `-Wall -Werror` or the equivalent is a good target to aim for.

**Pull request closed without merging**
