### PR TITLE
rename Status -> _Status, Bool -> _Bool for compatibility with X11 (bug #500)

### PR DESCRIPTION
**Pull request by SSE4**

### CODE REVIEW

**Comment by CaseyCarter** [comment]
All identifiers beginning with `_` followed by a capital letter are reserved to the C++ implementation. Using such an identifier has undefined behavior

**Comment by SSE4** [comment]
@CaseyCarter okay, what would you prefer? "Status_", or something else?

**Comment by ericniebler** [comment]
Trailing underscores would be fine.

**Comment by ericniebler** [comment]
Did you mean to close this?

**Comment by SSE4** [comment]
@ericniebler yes, I've opened new request with trailing underscores #502

**Pull request closed without merging**
