### PR TITLE
Cartesian fixes

### LINKED ISSUE #823: cartesian_products chunk not properly iterable
Using the current master branch, I am encountering a runtime error while using a `chunk`ed `cartesian_product`. I speculate that the inner range iterator/sentinel equality operator is the source of the trouble.

```cpp
#include <iostream>
#include <range/v3/all.hpp>

int main(){
  auto three = ranges::view::iota(0) | ranges::view::take_exactly(3);
  auto prod = ranges::view::cartesian_product(three, three);
  auto twoD = prod | ranges::view::chunk(3);

  int i = 0;
  RANGES_FOR(auto row, twoD){
    ++i; int j = 0;
    RANGES_FOR(auto col, row){
      std::cout << i << ',' << j << std::endl;
      ++j;
    }
  }
}
```

```
1,0
1,1
1,2
1,3
1,4
1,5
1,6
1,7
1,8
1,9
1,10
1,11
main: /home/apmccartney/range-v3/include/range/v3/view/cartesian_product.hpp:115: void ranges::v3::cartesian_product_view<Views>::cursor<IsConst>::next_(meta::v1::size_t<1>) [with bool IsConst = true; Views = {ranges::v3::detail::take_exactly_view_<ranges::v3::iota_view<int, void>, false>, ranges::v3::detail::take_exactly_view_<ranges::v3::iota_view<int, void>, false>}; meta::v1::size_t<1> = std::integral_constant<long unsigned int, 1>]: Assertion `i != last' failed.
```

I suspect this the result of an interaction between these views. This simpler example works as expect

```
#include <iostream>
#include <range/v3/all.hpp>

int main(){
  auto test = ranges::view::iota(9) | ranges::view::take_exactly(9) | ranges::view::chunk(3);
  int i = 0;
  RANGES_FOR(auto row, test){
    ++i; int j = 0;
    RANGES_FOR(auto col, row){
      std::cout << i << ',' << j << std::endl;
      ++j;
    }
  }
}
```

### PR DESCRIPTION
**Pull request by CaseyCarter**
* [take_view] Actually mark `const` overload of `begin_adaptor` as `const`
* [chunk_view]
  * Remove commented `CONCEPT_ASSERT`
  * Simplify `adaptor::read` by accepting `const&`
* Implement configuration/detection for `constexpr if`
* [cartesian_product] cleanups:
  * In `cursor::equal`, check from most-varying to least-varying iterator.
  * Simplify `cursor::distance_to`
  * Remove single-use type alias `pos_t`
  * Explain `check_at_end_`
  * Completely rewrite `advance`, it's a bit of a dumpster fire
  
  Fixes #823.

### CODE REVIEW

**Comment by ericniebler** [comment]
AppVeyor is failing with:

```
C:\projects\range-v3\include\range/v3/view/cartesian_product.hpp(173,25): error : implicit conversion loses integer precision: 'long long' to 'std::ptrdiff_t' (aka 'int') [-Werror,-Wshorten-64-to-32] [C:\projects\range-v3\build\test\view\view.cartesian_product.vcxproj]
                          + (std::get<N - 1>(that.its_) - std::get<N - 1>(its_));
```

**Comment by CaseyCarter** [comment]
> Fixes #823.

Prove it: where's the regression test?

**Comment by ericniebler** [comment]
We have a serious contended for "Most Annoyingly Nannying Warning Ever":

```
/home/travis/build/ericniebler/range-v3/test/view/cartesian_product.cpp:166:27: error: 
      loop variable 'x' is always a copy because the range of type
      'ranges::v3::cartesian_product_view<ranges::v3::detail::take_exactly_view_<ranges::v3::iota_view<int,
      void>, false>,
      ranges::v3::detail::take_exactly_view_<ranges::v3::iota_view<int, void>,
      false> >' does not return a reference [-Werror,-Wrange-loop-analysis]
        RANGES_FOR(auto&& x, prod) {
                          ^
```

**Comment by CaseyCarter** [comment]
> We have a serious contender for "Most Annoyingly Nannying Warning Ever":

I get the idea maybe for concrete types, but for `auto&&` this is simply begging to be disabled.

**Pull request merged**
