### PR TITLE
fix libstdcxx4.9 support and test clang+libstdc++ on travis (C++11 only)

### PR DESCRIPTION
**Pull request by gnzlbg**
Instead of checking for clang this checks for libc++.

### CODE REVIEW

**Comment by CaseyCarter** [comment]
This pessimizes clang+libstdc++ when libstdc++ >= 5. Why not simply implement the type traits under `ranges::v3::detail` for clang without libc++ and call it a day, e.g.:

```c++
#include <type_traits>
#if defined(__clang__) && !defined(_LIBCPP_VERSION)
    template<typename T>
    using is_trivially_copy_assignable =
        meta::bool_<__is_trivally_assignable(T &, T const&)>;

    template<typename T>
    using is_trivially_move_assignable =
        meta::bool_<__is_trivally_assignable(T &, T &&)>;

#elif defined(__GNUC__) && !defined(__clang__) && __GNUC__ < 5
    template<typename T>
    using is_trivially_copy_assignable = std::is_trivial<T>;
 
    template<typename T>
    using is_trivially_move_assignable = std::is_trivial<T>;

#else
using std::is_trivially_copy_assignable;
using std::is_trivially_move_assignable;
#endif
 ```
For bonus points. solve the `is_final` issue similarly ;)

**Comment by gnzlbg** [comment]
>This pessimizes clang+libstdc++ when libstdc++ >= 5

Is this because clang defines `__GNUC__` to 4 even when using libstdc++>=5?

>  Why not simply implement the type traits under ranges::v3::detail for clang without libc++ and call it a day,

Will update the PR.

**Comment by CaseyCarter** [comment]
> Is this because clang defines `__GNUC__` to `4` even when using libstdc++>=5?

Yip.

**Comment by CaseyCarter** [comment]
@gnzlbg Oops - you lost the Travis change when you re-pushed.

**Comment by gnzlbg** [comment]
Should be fixed now.

**Comment by ericniebler** [comment]
Thanks guys!

**Pull request merged**
