### PR TITLE
the views and actions no longer get their pipe operator from pipeable_base

### PR DESCRIPTION
**Pull request by ericniebler**
The idea here is to improve error messages when users try to pipe, e.g., temporary containers into view adaptors. It may also improve compile times marginally (?).

It is also a little janky to glom together views and actions into a single curried pipe (e.g., `auto pipe = view::FOO | action::BAR;`), although I might end up adding back support for that.

### CODE REVIEW

**Comment by h-2** [comment]
Just wanted to confirm that this PR fixes #1305 for me.

**Comment by ericniebler** [comment]
Yes, and I'm using this as an opportunity to clean some other things up besides. I hope to finish this up after my CppCon talk.

**Comment by CaseyCarter** [comment]
....5 hours later, Appveyor finishes the `/branch` build and starts the `/pr` build...

I'm working on an Appveyor change. Feel free to merge this without waiting for Appveyor to finish.

**Comment by h-2** [comment]
Anything I can do to help this find its way into master? :smile_cat: 

Thank you very much!

**Comment by ericniebler** [comment]
I beg your patience. The Belfast mailing deadline looms.

**Comment by h-2** [comment]
Sorry, I didn't want to annoy you! I took Casey's last comment as indicating it was done and thought it might have slipped from the radar, but I know these things take time and I am sure you have many other things on your plate.

**Pull request merged**
